DELETE http://localhost:3003/api/blogs/670e491a288c7fe238541326
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFrb3IiLCJpZCI6IjY3MGUwZDg1MjQ5NTg5MmE4ZDc4ODkxOSIsImlhdCI6MTcyODk4OTQ4MywiZXhwIjoxNzI4OTkzMDgzfQ.6Ngbu2tLC_QVa7pwwUucvyz7okbmOzcB7ri5GkyMCvc